import '@/styles/globals.css'

import type { Metadata } from 'next'

import { poppins, raleway } from '@/fonts/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${raleway.variable}`}>
      <body>{children}</body>
    </html>
  )
}
