import '@/styles/globals.css'

import type { Metadata } from 'next'

import { Header } from '@/components/layout/header'
import { poppins, raleway } from '@/fonts/fonts'

import { Provider } from './providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${raleway.variable}`}>
      <body className="flex min-h-screen w-full flex-col bg-background antialiased">
        <Provider>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  )
}
